### ISSUE TITLE
link broken gp2swiss.txt

### ISSUE THREAD

**Issue by sinanshi** [Bahler-Lab/yogy#4]
link broken.
ftp://ftp.sanger.ac.uk/pub/yeast/pombe/Mappings/gp2swiss.txt

https://github.com/Bahler-Lab/yogy/blob/master/YogiUp/perl/update_database.pl#L215

**Comment by dbitton** [comment]
You have that file :+1: 
wget ftp://ftp.ebi.ac.uk/pub/databases/pombase/pombe/Mappings/sysID2product.tsv

**Comment by sinanshi** [comment]
Do you think this one should be ftp://ftp.ebi.ac.uk/pub/databases/pombase/pombe/Mappings/PomBase2UniProt.tsv Because the original file has systematic names and uniport.

**Comment by dbitton** [comment]
swiss and uniprot are the same

**Comment by sinanshi** [comment]
Yes, there is no uniprot infroamtion on `sysID2product.tsv`. the uniprot value is in `PomBase2UniProt.tsv`

**Comment by dbitton** [comment]
oops sorry my mistake, yes!

**Comment by sinanshi** [comment]
thank, it works.
