### ISSUE TITLE
link broken `pompep`

### ISSUE THREAD

**Issue by sinanshi** [Bahler-Lab/yogy#5]
`ftp://ftp.sanger.ac.uk/pub/yeast/pombe/Protein_data/pompep`
https://github.com/Bahler-Lab/yogy/blob/master/YogiUp/perl/update_database.pl#L234

**Comment by dbitton** [comment]
I gave this link in previous issue
ftp://ftp.ebi.ac.uk/pub/databases/pombase/FASTA/pep.fa.gz

**Comment by sinanshi** [comment]
So far, yogy_polulate has ran through. So I will start doing the rest part of `run_db.csh`
