### ISSUE TITLE
OrthoMCL link broken

### ISSUE THREAD

**Issue by sinanshi** [Bahler-Lab/yogy#9]
http://orthomcl.cbil.upenn.edu/ORTHOMCL_DB/all_orthomcl.out
all_orthomcl.out

http://orthomcl.cbil.upenn.edu/ORTHOMCL_DB/BAE_geneid_anno
BAE_geneid_anno

**Comment by dbitton** [comment]
It seems that this database is not updated often I found this link where these files are found but they probably very old
http://www.orthomcl.org/common/downloads/1.0/ 
please explore http://www.orthomcl.org/orthomcl/

**Comment by sinanshi** [comment]
done
